/* generated from model SDBasis */
/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.lang.sdbasis._cocos;


/* generated by template cd2java.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.se_rwth.commons.SourcePosition;



/* Hookpoint: ClassContent:Imports */



/* Hookpoint: ClassContent:Annotations */

 public  class SDBasisCoCoChecker  {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 protected  de.monticore.lang.sdbasis._visitor.SDBasisTraverser traverser
  
;


    /* generated by template cd2java.Constructor*/
 public  SDBasisCoCoChecker()
 {
  /* generated by template _cocos.CoCoCheckerConstructor*/

  traverser = de.monticore.lang.sdbasis.SDBasisMill.inheritanceTraverser();
}


    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  de.monticore.lang.sdbasis._visitor.SDBasisTraverser getTraverser ()

 {
    /* generated by template methods.Get*/

return this.traverser;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void setTraverser (de.monticore.lang.sdbasis._visitor.SDBasisTraverser traverser)

 {
    /* generated by template methods.Set*/

this.traverser = traverser;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.lang.sdbasis._cocos.SDBasisCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getSDBasisVisitorList().forEach(s -> traverser.add4SDBasis(s));
  checker.getTraverser().getMCBasicTypesVisitorList().forEach(s -> traverser.add4MCBasicTypes(s));
  checker.getTraverser().getBasicSymbolsVisitorList().forEach(s -> traverser.add4BasicSymbols(s));
  checker.getTraverser().getExpressionsBasisVisitorList().forEach(s -> traverser.add4ExpressionsBasis(s));
  checker.getTraverser().getUMLStereotypeVisitorList().forEach(s -> traverser.add4UMLStereotype(s));
  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));
  checker.getTraverser().getMCLiteralsBasisVisitorList().forEach(s -> traverser.add4MCLiteralsBasis(s));
  checker.getTraverser().getMCCommonLiteralsVisitorList().forEach(s -> traverser.add4MCCommonLiterals(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.lang.sdbasis._ast.ASTSDBasisNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDArtifactCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSequenceDiagramCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDBodyCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDCompleteModifierCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDFreeModifierCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDInitialModifierCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDVisibleModifierCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDObjectCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDObjectSourceCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDObjectTargetCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDSendMessageCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDActivityBarCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDModifierCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDElementCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDInteractionCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDSourceCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDTargetCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDActionCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.lang.sdbasis._cocos.SDBasisASTSDBasisNodeCoCo coco)

 {
    traverser.add4SDBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.types.mcbasictypes._cocos.MCBasicTypesCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getMCBasicTypesVisitorList().forEach(s -> traverser.add4MCBasicTypes(s));
  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.types.mcbasictypes._ast.ASTMCBasicTypesNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCQualifiedNameCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCPackageDeclarationCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCImportStatementCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCPrimitiveTypeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCQualifiedTypeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCReturnTypeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCVoidTypeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCTypeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCObjectTypeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.types.mcbasictypes._cocos.MCBasicTypesASTMCBasicTypesNodeCoCo coco)

 {
    traverser.add4MCBasicTypes(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getBasicSymbolsVisitorList().forEach(s -> traverser.add4BasicSymbols(s));
  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.symbols.basicsymbols._ast.ASTBasicSymbolsNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsASTDiagramCoCo coco)

 {
    traverser.add4BasicSymbols(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsASTTypeCoCo coco)

 {
    traverser.add4BasicSymbols(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsASTTypeVarCoCo coco)

 {
    traverser.add4BasicSymbols(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsASTVariableCoCo coco)

 {
    traverser.add4BasicSymbols(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsASTFunctionCoCo coco)

 {
    traverser.add4BasicSymbols(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.symbols.basicsymbols._cocos.BasicSymbolsASTBasicSymbolsNodeCoCo coco)

 {
    traverser.add4BasicSymbols(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.expressions.expressionsbasis._cocos.ExpressionsBasisCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getExpressionsBasisVisitorList().forEach(s -> traverser.add4ExpressionsBasis(s));
  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));
  checker.getTraverser().getMCLiteralsBasisVisitorList().forEach(s -> traverser.add4MCLiteralsBasis(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.expressions.expressionsbasis._ast.ASTExpressionsBasisNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.expressions.expressionsbasis._cocos.ExpressionsBasisASTNameExpressionCoCo coco)

 {
    traverser.add4ExpressionsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.expressions.expressionsbasis._cocos.ExpressionsBasisASTLiteralExpressionCoCo coco)

 {
    traverser.add4ExpressionsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.expressions.expressionsbasis._cocos.ExpressionsBasisASTArgumentsCoCo coco)

 {
    traverser.add4ExpressionsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.expressions.expressionsbasis._cocos.ExpressionsBasisASTExpressionCoCo coco)

 {
    traverser.add4ExpressionsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.expressions.expressionsbasis._cocos.ExpressionsBasisASTExpressionsBasisNodeCoCo coco)

 {
    traverser.add4ExpressionsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.umlstereotype._cocos.UMLStereotypeCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getUMLStereotypeVisitorList().forEach(s -> traverser.add4UMLStereotype(s));
  checker.getTraverser().getMCCommonLiteralsVisitorList().forEach(s -> traverser.add4MCCommonLiterals(s));
  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));
  checker.getTraverser().getMCLiteralsBasisVisitorList().forEach(s -> traverser.add4MCLiteralsBasis(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.umlstereotype._ast.ASTUMLStereotypeNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.umlstereotype._cocos.UMLStereotypeASTStereotypeCoCo coco)

 {
    traverser.add4UMLStereotype(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.umlstereotype._cocos.UMLStereotypeASTStereoValueCoCo coco)

 {
    traverser.add4UMLStereotype(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.umlstereotype._cocos.UMLStereotypeASTUMLStereotypeNodeCoCo coco)

 {
    traverser.add4UMLStereotype(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.mcbasics._cocos.MCBasicsCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.mcbasics._ast.ASTMCBasicsNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.mcbasics._cocos.MCBasicsASTMCBasicsNodeCoCo coco)

 {
    traverser.add4MCBasics(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.literals.mcliteralsbasis._cocos.MCLiteralsBasisCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getMCLiteralsBasisVisitorList().forEach(s -> traverser.add4MCLiteralsBasis(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.literals.mcliteralsbasis._ast.ASTMCLiteralsBasisNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mcliteralsbasis._cocos.MCLiteralsBasisASTLiteralCoCo coco)

 {
    traverser.add4MCLiteralsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mcliteralsbasis._cocos.MCLiteralsBasisASTMCLiteralsBasisNodeCoCo coco)

 {
    traverser.add4MCLiteralsBasis(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addChecker (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsCoCoChecker checker)

 {
    /* generated by template _cocos.AddChecker*/


  checker.getTraverser().getMCCommonLiteralsVisitorList().forEach(s -> traverser.add4MCCommonLiterals(s));
  checker.getTraverser().getMCBasicsVisitorList().forEach(s -> traverser.add4MCBasics(s));
  checker.getTraverser().getMCLiteralsBasisVisitorList().forEach(s -> traverser.add4MCLiteralsBasis(s));

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void checkAll (de.monticore.literals.mccommonliterals._ast.ASTMCCommonLiteralsNode node)

 {
    node.accept(getTraverser());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTNullLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTBooleanLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTCharLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTStringLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTNatLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTSignedNatLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTBasicLongLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTSignedBasicLongLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTBasicFloatLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTSignedBasicFloatLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTBasicDoubleLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTSignedBasicDoubleLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTSignedLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTNumericLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTSignedNumericLiteralCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addCoCo (de.monticore.literals.mccommonliterals._cocos.MCCommonLiteralsASTMCCommonLiteralsNodeCoCo coco)

 {
    traverser.add4MCCommonLiterals(coco);
}


}


