/* generated by template _lsp.features.hover.HoverProvider*/

package de.monticore.lang.sd4development._lsp.features.hover;

import de.monticore.symboltable.ISymbol;
import de.monticore.lang.sd4development._lsp.*;

import de.mclsg.lsp.ISymbolUsageResolutionProvider;
import de.mclsg.lsp.document_management.*;
import de.mclsg.lsp.features.CommonProvider;
import de.mclsg.lsp.features.HoverProvider;
import org.eclipse.lsp4j.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


public class SD4DevelopmentHoverProvider extends de.mclsg.lsp.features.hover.CommonHoverProvider {
  public SD4DevelopmentHoverProvider(DocumentManager documentManager, ISymbolUsageResolutionProvider symbolUsageResolutionProvider) {
    super(documentManager, symbolUsageResolutionProvider);
    addJavaDocHoverRule(documentManager, symbolUsageResolutionProvider);
  }

  protected void addJavaDocHoverRule(DocumentManager documentManager, ISymbolUsageResolutionProvider symbolUsageResolutionProvider){
    addHoverRule(new de.mclsg.lsp.features.hover.JavaDocHoverRule(documentManager, symbolUsageResolutionProvider));
  }
}
