/* generated from model SD4Development */
/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.lang.sd4development._ast;


/* generated by template cd2java.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.se_rwth.commons.SourcePosition;



/* Hookpoint: ClassContent:Imports */



/* Hookpoint: ClassContent:Annotations */

 public  class ASTConstantsSD4Development  {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 public  final  static  String LANGUAGE
  = "SD4Development"
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 public  final  static  int DEFAULT
  = 0
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 public  final  static  int STATIC
  = 1
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 public  final  static  int TRIGGER
  = 2
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 public  static  String[] superGrammars
  = {"de.monticore.lang.SDBasis", "de.monticore.literals.MCCommonLiterals", "de.monticore.expressions.CommonExpressions", "de.monticore.ocl.OCLExpressions", "de.monticore.symbols.OOSymbols", "de.monticore.types.MCBasicTypes", "de.monticore.symbols.BasicSymbols", "de.monticore.expressions.ExpressionsBasis", "de.monticore.UMLStereotype", "de.monticore.MCBasics", "de.monticore.literals.MCLiteralsBasis"}
;


    /* generated by template cd2java.Constructor*/
 public  ASTConstantsSD4Development()
 {
  /* generated by template cd2java.EmptyBody*/
// empty body

}


    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  static  Collection<String> getAllLanguages ()

 {
    /* generated by template _ast.ast_constants.GetAllLanguages*/


  Collection<String> allLanguages = new LinkedHashSet<>();
    allLanguages.addAll(de.monticore.lang.sdbasis._ast.ASTConstantsSDBasis.getAllLanguages());
    allLanguages.addAll(de.monticore.literals.mccommonliterals._ast.ASTConstantsMCCommonLiterals.getAllLanguages());
    allLanguages.addAll(de.monticore.expressions.commonexpressions._ast.ASTConstantsCommonExpressions.getAllLanguages());
    allLanguages.addAll(de.monticore.ocl.oclexpressions._ast.ASTConstantsOCLExpressions.getAllLanguages());
    allLanguages.addAll(de.monticore.symbols.oosymbols._ast.ASTConstantsOOSymbols.getAllLanguages());
    allLanguages.addAll(de.monticore.types.mcbasictypes._ast.ASTConstantsMCBasicTypes.getAllLanguages());
    allLanguages.addAll(de.monticore.symbols.basicsymbols._ast.ASTConstantsBasicSymbols.getAllLanguages());
    allLanguages.addAll(de.monticore.expressions.expressionsbasis._ast.ASTConstantsExpressionsBasis.getAllLanguages());
    allLanguages.addAll(de.monticore.umlstereotype._ast.ASTConstantsUMLStereotype.getAllLanguages());
    allLanguages.addAll(de.monticore.mcbasics._ast.ASTConstantsMCBasics.getAllLanguages());
    allLanguages.addAll(de.monticore.literals.mcliteralsbasis._ast.ASTConstantsMCLiteralsBasis.getAllLanguages());
  allLanguages.add(LANGUAGE);
  return allLanguages;
}


}


