/* generated from model SD4Development */
/* generated by template cd2java.Interface*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: InterfaceContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.lang.sd4development._symboltable;


/* generated by template cd2java.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.se_rwth.commons.SourcePosition;

import de.monticore.symboltable.*;


/* Hookpoint: InterfaceContent:Imports */



/* Hookpoint: InterfaceContent:Annotations */

 public  interface ISD4DevelopmentScope extends de.monticore.lang.sdbasis._symboltable.ISDBasisScope,de.monticore.literals.mccommonliterals._symboltable.IMCCommonLiteralsScope,de.monticore.expressions.commonexpressions._symboltable.ICommonExpressionsScope,de.monticore.ocl.oclexpressions._symboltable.IOCLExpressionsScope,de.monticore.symbols.oosymbols._symboltable.IOOSymbolsScope  { 
/* Hookpoint: InterfaceContent:Elements */


  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  List<? extends ISD4DevelopmentScope> getSubScopes ()

;
  default /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addSubScope (ISD4DevelopmentScope subScope)

 {
    Log.error("0xA7014x67198 The method \"addSubScope\" of interface \"ISD4DevelopmentScope\" is not implemented.");
}

  default /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void removeSubScope (ISD4DevelopmentScope subScope)

 {
    Log.error("0xA7013x43371 The method \"removeSubScope\" of interface \"ISD4DevelopmentScope\" is not implemented.");
}

  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  ISD4DevelopmentScope getEnclosingScope ()

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void setEnclosingScope (ISD4DevelopmentScope enclosingScope)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser visitor)

;
  default /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  int getSymbolsSize ()

 {
    /* generated by template _symboltable.iscope.GetSymbolSize*/


Set<ISymbol> allSymbols = new HashSet<>();
    allSymbols.addAll(getOOTypeSymbols().values());
    allSymbols.addAll(getFieldSymbols().values());
    allSymbols.addAll(getMethodSymbols().values());
    allSymbols.addAll(getDiagramSymbols().values());
    allSymbols.addAll(getTypeSymbols().values());
    allSymbols.addAll(getTypeVarSymbols().values());
    allSymbols.addAll(getVariableSymbols().values());
    allSymbols.addAll(getFunctionSymbols().values());
return allSymbols.size();
}

  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.lang.sdbasis._visitor.SDBasisTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.literals.mccommonliterals._visitor.MCCommonLiteralsTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.expressions.commonexpressions._visitor.CommonExpressionsTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.ocl.oclexpressions._visitor.OCLExpressionsTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.symbols.oosymbols._visitor.OOSymbolsTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.types.mcbasictypes._visitor.MCBasicTypesTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.symbols.basicsymbols._visitor.BasicSymbolsTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.expressions.expressionsbasis._visitor.ExpressionsBasisTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.umlstereotype._visitor.UMLStereotypeTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.mcbasics._visitor.MCBasicsTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.literals.mcliteralsbasis._visitor.MCLiteralsBasisTraverser visitor)

;
  /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 abstract  public  void accept (de.monticore.visitor.ITraverser visitor)

;
}
