/* generated from model SD4Development */
/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.lang.sd4development._symboltable;


/* generated by template cd2java.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.se_rwth.commons.SourcePosition;

import de.monticore.symboltable.*;


/* Hookpoint: ClassContent:Imports */



/* Hookpoint: ClassContent:Annotations */

 abstract  public  class SD4DevelopmentArtifactScopeTOP extends de.monticore.lang.sd4development._symboltable.SD4DevelopmentScope  implements de.monticore.lang.sd4development._symboltable.ISD4DevelopmentArtifactScope {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 protected  String packageName
  
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 protected  List<de.monticore.symboltable.ImportStatement> imports
  
;


    /* generated by template cd2java.Constructor*/
 public  SD4DevelopmentArtifactScopeTOP(String packageName,List<de.monticore.symboltable.ImportStatement> imports)
 {
  this(Optional.empty(), packageName, imports);
}

    /* generated by template cd2java.Constructor*/
 public  SD4DevelopmentArtifactScopeTOP(Optional<de.monticore.lang.sd4development._symboltable.ISD4DevelopmentScope> enclosingScope,String packageName,List<de.monticore.symboltable.ImportStatement> imports)
 {
  /* generated by template _symboltable.artifactscope.ConstructorArtifactScope*/
  super(true);
  if (enclosingScope.isPresent()) {
    setEnclosingScope(enclosingScope.get());
  }
  setExportingSymbols(true);
  Log.errorIfNull(packageName);
  Log.errorIfNull(imports);

  if (!packageName.isEmpty()) {
    this.packageName = packageName.endsWith(".") ? packageName.substring(0, packageName.length() - 1) : packageName;
  } else {
    // default package
    this.packageName = "";
  }

  this.imports = java.util.List.copyOf(imports);
}

    /* generated by template cd2java.Constructor*/
 public  SD4DevelopmentArtifactScopeTOP()
 {
  this("", new java.util.ArrayList<>());
}


    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  String getPackageName ()

 {
    /* generated by template methods.Get*/

return this.packageName;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void setPackageName (String packageName)

 {
    /* generated by template methods.Set*/

this.packageName = packageName;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  List<de.monticore.symboltable.ImportStatement> getImportsList ()

 {
    /* generated by template methods.Get*/

return this.imports;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void setImportsList (List<de.monticore.symboltable.ImportStatement> imports)

 {
    /* generated by template methods.Set*/

this.imports = imports;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  boolean isPresentName ()

 {
    /* generated by template _symboltable.artifactscope.IsPresentName*/
  if (!super.isPresentName()) {
    final Optional<de.monticore.symboltable.ISymbol> topLevelSymbol = getTopLevelSymbol();
    if (topLevelSymbol.isPresent()) {
      setName(topLevelSymbol.get().getName());
    }
  }
  return this.name.isPresent();
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  String getName ()

 {
    /* generated by template _symboltable.artifactscope.GetName*/
  if (!super.isPresentName()) {
    final Optional<de.monticore.symboltable.ISymbol> topLevelSymbol = getTopLevelSymbol();
    if (topLevelSymbol.isPresent()) {
      setName(topLevelSymbol.get().getName());
    }
  }
  return super.getName();
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void setEnclosingScope (de.monticore.lang.sd4development._symboltable.ISD4DevelopmentScope enclosingScope)

 {
    /* generated by template _symboltable.artifactscope.SetEnclosingScope*/

if(enclosingScope != null && !(enclosingScope instanceof SD4DevelopmentGlobalScope)){
  Log.warn("0xA1039x37002 The artifact scope " + (isPresentName() ? getName() : "") + " should have a global scope as enclosing scope or no "
    + "enclosing scope at all.");
}
super.setEnclosingScope(enclosingScope);

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser visitor)

 {
    /* generated by template _symboltable.AcceptTop*/

  if (this instanceof SD4DevelopmentArtifactScope) {
    visitor.handle((SD4DevelopmentArtifactScope) this);
  } else {
    throw new UnsupportedOperationException("0xA7010x37002 Only handwritten class SD4DevelopmentArtifactScope is supported for the visitor");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.lang.sdbasis._visitor.SDBasisTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x22522 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.lang.sdbasis._visitor.SDBasisTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.literals.mccommonliterals._visitor.MCCommonLiteralsTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x94788 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.literals.mccommonliterals._visitor.MCCommonLiteralsTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.expressions.commonexpressions._visitor.CommonExpressionsTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x70059 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.expressions.commonexpressions._visitor.CommonExpressionsTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.ocl.oclexpressions._visitor.OCLExpressionsTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x82006 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.ocl.oclexpressions._visitor.OCLExpressionsTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.symbols.oosymbols._visitor.OOSymbolsTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x76171 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.symbols.oosymbols._visitor.OOSymbolsTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.types.mcbasictypes._visitor.MCBasicTypesTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x21135 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.types.mcbasictypes._visitor.MCBasicTypesTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.symbols.basicsymbols._visitor.BasicSymbolsTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x68633 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.symbols.basicsymbols._visitor.BasicSymbolsTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.expressions.expressionsbasis._visitor.ExpressionsBasisTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x90515 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.expressions.expressionsbasis._visitor.ExpressionsBasisTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.umlstereotype._visitor.UMLStereotypeTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x07624 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.umlstereotype._visitor.UMLStereotypeTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.mcbasics._visitor.MCBasicsTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x75728 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.mcbasics._visitor.MCBasicsTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.literals.mcliteralsbasis._visitor.MCLiteralsBasisTraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x80848 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.literals.mcliteralsbasis._visitor.MCLiteralsBasisTraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void accept (de.monticore.visitor.ITraverser visitor)

 {
    /* generated by template data.AcceptSuper*/

  if (visitor instanceof de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) {
    accept((de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser) visitor);
  } else {
    de.se_rwth.commons.logging.Log.error("0xA7011x46976 Scope type SD4DevelopmentArtifactScope expected a visitor of type de.monticore.lang.sd4development._visitor.SD4DevelopmentTraverser, but got de.monticore.visitor.ITraverser. Visitors of a super language may not be used on Symbols containing nodes of the sub language. Use a visitor of the sub language.");
  }

}


}


