/* generated from model SDBasis */
/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.lang.sdbasis._symboltable;


/* generated by template cd2java.Imports*/

import java.util.*;
import java.util.function.*;
import java.util.stream.Stream;
import de.se_rwth.commons.logging.Log;
import de.se_rwth.commons.SourcePosition;



/* Hookpoint: ClassContent:Imports */



/* Hookpoint: ClassContent:Annotations */

 abstract  public  class SDBasisScopesGenitorTOP  implements de.monticore.lang.sdbasis._visitor.SDBasisVisitor2,de.monticore.lang.sdbasis._visitor.SDBasisHandler {

/* Hookpoint: ClassContent:Elements */

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 protected  Deque<de.monticore.lang.sdbasis._symboltable.ISDBasisScope> scopeStack
  = new java.util.ArrayDeque<>()
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 protected  de.monticore.lang.sdbasis._visitor.SDBasisTraverser traverser
  
;

    /* generated by template cd2java.Attribute*/

/* Hookpoint: AttributeContent:Annotations */
 protected  de.monticore.lang.sdbasis._symboltable.ISDBasisScope firstCreatedScope
  
;


    /* generated by template cd2java.Constructor*/
 public  SDBasisScopesGenitorTOP()
 {
  this.scopeStack = new ArrayDeque<>();
}


    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  de.monticore.lang.sdbasis._visitor.SDBasisTraverser getTraverser ()

 {
    /* generated by template methods.Get*/

return this.traverser;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void setTraverser (de.monticore.lang.sdbasis._visitor.SDBasisTraverser traverser)

 {
    /* generated by template methods.Set*/

this.traverser = traverser;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  de.monticore.lang.sdbasis._symboltable.ISDBasisScope getFirstCreatedScope ()

 {
    /* generated by template methods.Get*/

return this.firstCreatedScope;

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  de.monticore.lang.sdbasis._symboltable.ISDBasisArtifactScope createFromAST (de.monticore.lang.sdbasis._ast.ASTSDArtifact rootNode)

 {
    /* generated by template _symboltable.scopesgenitor.CreateFromAST*/

  Log.errorIfNull(rootNode, "0xA7004x02630 Error by creating of the SDBasisScopesGenitor symbol table: top ast node is null");
  ISDBasisArtifactScope artifactScope = de.monticore.lang.sdbasis.SDBasisMill.artifactScope();
  artifactScope.setPackageName("");
  artifactScope.setImportsList(new ArrayList<>());
  artifactScope.setAstNode(rootNode);
  putOnStack(artifactScope);
  initArtifactScopeHP1(artifactScope);
  rootNode.accept(getTraverser());
  initArtifactScopeHP2(artifactScope);
  scopeStack.remove(artifactScope);
  return artifactScope;
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void putOnStack (de.monticore.lang.sdbasis._symboltable.ISDBasisScope scope)

 {
    /* generated by template _symboltable.scopesgenitor.PutOnStack*/
  Log.errorIfNull(scope);

if (scope.getEnclosingScope() == null && getCurrentScope().isPresent()) {
    scope.setEnclosingScope(getCurrentScope().get());
    getCurrentScope().get().addSubScope(scope);
} else if (scope.getEnclosingScope() != null && getCurrentScope().isPresent()) {
    if (scope.getEnclosingScope() != getCurrentScope().get()) {
      Log.warn("0xA1043 The enclosing scope is not the same as the current scope on the stack.");
    }
  }

  if (firstCreatedScope == null) {
    firstCreatedScope = scope;
  }

  scopeStack.addLast(scope);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  final  Optional<de.monticore.lang.sdbasis._symboltable.ISDBasisScope> getCurrentScope ()

 {
    return Optional.ofNullable(scopeStack.peekLast());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  final  Optional<de.monticore.lang.sdbasis._symboltable.ISDBasisScope> removeCurrentScope ()

 {
    return Optional.ofNullable(scopeStack.pollLast());
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void setScopeStack (Deque<? extends de.monticore.lang.sdbasis._symboltable.ISDBasisScope> scopeStack)

 {
    this.scopeStack = Log.errorIfNull((Deque<de.monticore.lang.sdbasis._symboltable.ISDBasisScope>)scopeStack);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  de.monticore.lang.sdbasis._symboltable.ISDBasisScope createScope (boolean shadowing)

 {
    /* generated by template _symboltable.scopesgenitor.CreateScope*/

  de.monticore.lang.sdbasis._symboltable.ISDBasisScope scope = de.monticore.lang.sdbasis.SDBasisMill.scope();
  scope.setShadowing(shadowing);
  return scope;
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSequenceDiagram node)

 {
    /* generated by template _symboltable.scopesgenitor.Visit4SSC*/

  de.monticore.symbols.basicsymbols._symboltable.DiagramSymbol symbol = de.monticore.lang.sdbasis.SDBasisMill.diagramSymbolBuilder().setName(node.getName()).build();
  if (getCurrentScope().isPresent()) {
    getCurrentScope().get().add(symbol);
  } else {
    Log.warn("0xA5021x17076 Symbol cannot be added to current scope, since no scope exists.");
  }
  // symbol -> ast
  symbol.setAstNode(node);

  // ast -> symbol
  node.setSymbol(symbol);
  node.setEnclosingScope(symbol.getEnclosingScope());

  initDiagramHP1(node.getSymbol());

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void endVisit (de.monticore.lang.sdbasis._ast.ASTSequenceDiagram node)

 {
    /* generated by template _symboltable.scopesgenitor.EndVisitSymbol*/

  if(node.isPresentSymbol()){
    initDiagramHP2(node.getSymbol());
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDObject node)

 {
    /* generated by template _symboltable.scopesgenitor.Visit4SSC*/

  de.monticore.symbols.basicsymbols._symboltable.VariableSymbol symbol = de.monticore.lang.sdbasis.SDBasisMill.variableSymbolBuilder().setName(node.getName()).build();
  if (getCurrentScope().isPresent()) {
    getCurrentScope().get().add(symbol);
  } else {
    Log.warn("0xA5021x87549 Symbol cannot be added to current scope, since no scope exists.");
  }
  // symbol -> ast
  symbol.setAstNode(node);

  // ast -> symbol
  node.setSymbol(symbol);
  node.setEnclosingScope(symbol.getEnclosingScope());

  initVariableHP1(node.getSymbol());

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void endVisit (de.monticore.lang.sdbasis._ast.ASTSDObject node)

 {
    /* generated by template _symboltable.scopesgenitor.EndVisitSymbol*/

  if(node.isPresentSymbol()){
    initVariableHP2(node.getSymbol());
  }

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initDiagramHP1 (de.monticore.symbols.basicsymbols._symboltable.DiagramSymbol symbol)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initDiagramHP2 (de.monticore.symbols.basicsymbols._symboltable.DiagramSymbol symbol)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initVariableHP1 (de.monticore.symbols.basicsymbols._symboltable.VariableSymbol symbol)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initVariableHP2 (de.monticore.symbols.basicsymbols._symboltable.VariableSymbol symbol)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDArtifact node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDCompleteModifier node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDFreeModifier node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDInitialModifier node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDVisibleModifier node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDObjectSource node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDObjectTarget node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDSendMessage node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDActivityBar node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitNoSymbol*/
  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
              + "\", because no scope is set yet!");
  }
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void visit (de.monticore.lang.sdbasis._ast.ASTSDBody node)

 {
    /* generated by template _symboltable.scopesgenitor.VisitScope4SSC*/

  if (getCurrentScope().isPresent()) {
    node.setEnclosingScope(getCurrentScope().get());
  }
  else {
    Log.error("Could not set enclosing scope of ASTNode \"" + node
      + "\", because no scope is set yet!");
  }
  de.monticore.lang.sdbasis._symboltable.ISDBasisScope scope = createScope(false);
  putOnStack(scope);
  // scope -> ast
  scope.setAstNode(node);

  // ast -> scope
  node.setSpannedScope(scope);
  initScopeHP1(scope);
}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void endVisit (de.monticore.lang.sdbasis._ast.ASTSDBody node)

 {
    /* generated by template _symboltable.scopesgenitor.EndVisitScope4SSC*/

removeCurrentScope();
initScopeHP2(node.getSpannedScope());

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initScopeHP1 (de.monticore.lang.sdbasis._symboltable.ISDBasisScope scope)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initScopeHP2 (de.monticore.lang.sdbasis._symboltable.ISDBasisScope scope)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initArtifactScopeHP1 (de.monticore.lang.sdbasis._symboltable.ISDBasisArtifactScope scope)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 protected  void initArtifactScopeHP2 (de.monticore.lang.sdbasis._symboltable.ISDBasisArtifactScope scope)

 {
    /* generated by template cd2java.EmptyBody*/
// empty body

}

    /* generated by template cd2java.Method*/

/* Hookpoint: MethodContent:Annotations */
 public  void addToScopeStack (de.monticore.lang.sdbasis._symboltable.ISDBasisScope scope)

 {
    scopeStack.addLast(scope);
}


}


