/* generated by template parser.ParserInfoForSuperLang*/

package de.monticore.lang.sd4development._parser._auxiliary;

import de.monticore.lang.sd4development._parser.SD4DevelopmentParserInfo;
import de.monticore.literals.mccommonliterals._parser.EmptyMCCommonLiteralsParserInfo;

public class SD4DevelopmentParserInfoForMCCommonLiterals extends EmptyMCCommonLiteralsParserInfo {
  protected boolean _stateReferencesVariableSymbol(int state){
    return SD4DevelopmentParserInfo.stateReferencesVariableSymbol(state);
  }
  protected boolean _stateHasUsageNameParts(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameParts(state);
  }
  protected boolean _stateHasUsageNameMCQualifiedName(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameMCQualifiedName(state);
  }
  protected boolean _stateHasUsageNameMCVoidType(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameMCVoidType(state);
  }
  protected boolean _stateHasUsageNameMCType(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameMCType(state);
  }
  protected boolean _stateHasUsageNameName(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameName(state);
  }
  protected boolean _stateHasUsageNameLiteral(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameLiteral(state);
  }
  protected boolean _stateHasUsageNameExpression(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameExpression(state);
  }
  protected boolean _stateHasUsageNameThenExpression(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameThenExpression(state);
  }
  protected boolean _stateHasUsageNameElseExpression(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameElseExpression(state);
  }
  protected boolean _stateHasUsageNameCondition(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameCondition(state);
  }
  protected boolean _stateHasUsageNameInDeclaration(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameInDeclaration(state);
  }
  protected boolean _stateHasUsageNameOCLVariableDeclaration(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameOCLVariableDeclaration(state);
  }
  protected boolean _stateHasUsageNameIteration(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameIteration(state);
  }
  protected boolean _stateHasUsageNameInit(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameInit(state);
  }
  protected boolean _stateHasUsageNameValue(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameValue(state);
  }
  protected boolean _stateHasUsageNameInDeclarationVariable(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameInDeclarationVariable(state);
  }
  protected boolean _stateHasUsageNameSource(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSource(state);
  }
  protected boolean _stateHasUsageNameDigits(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameDigits(state);
  }
  protected boolean _stateHasUsageNamePre(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNamePre(state);
  }
  protected boolean _stateHasUsageNamePost(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNamePost(state);
  }
  protected boolean _stateHasUsageNameValues(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameValues(state);
  }
  protected boolean _stateHasUsageNameText(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameText(state);
  }
  protected boolean _stateHasUsageNamePackageDeclaration(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNamePackageDeclaration(state);
  }
  protected boolean _stateHasUsageNameMCImportStatement(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameMCImportStatement(state);
  }
  protected boolean _stateHasUsageNameSequenceDiagram(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSequenceDiagram(state);
  }
  protected boolean _stateHasUsageNameStereotype(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameStereotype(state);
  }
  protected boolean _stateHasUsageNameSDModifier(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDModifier(state);
  }
  protected boolean _stateHasUsageNameSDObject(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDObject(state);
  }
  protected boolean _stateHasUsageNameSDBody(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDBody(state);
  }
  protected boolean _stateHasUsageNameSDElement(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDElement(state);
  }
  protected boolean _stateHasUsageNameMCObjectType(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameMCObjectType(state);
  }
  protected boolean _stateHasUsageNameSDSource(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDSource(state);
  }
  protected boolean _stateHasUsageNameSDTarget(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDTarget(state);
  }
  protected boolean _stateHasUsageNameSDAction(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDAction(state);
  }
  protected boolean _stateHasUsageNameSDActivityBar(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDActivityBar(state);
  }
  protected boolean _stateHasUsageNameArguments(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameArguments(state);
  }
  protected boolean _stateHasUsageNameDeclarationType(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameDeclarationType(state);
  }
  protected boolean _stateHasUsageNameInitializationType(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameInitializationType(state);
  }
  protected boolean _stateHasUsageNameSDEndCallArrow(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameSDEndCallArrow(state);
  }
  protected boolean _stateHasUsageNameAssignment(int state){
    return SD4DevelopmentParserInfo.stateHasUsageNameAssignment(state);
  }

  protected boolean _stateDefinesName(int state){
    return SD4DevelopmentParserInfo.stateDefinesName(state);
  }
}
