/* generated by template _lsp.SyntaxHighlightingService*/

package de.monticore.lang.sdbasis._lsp;

import de.monticore.lang.sdbasis._lsp.features.syntax_highlighting.SDBasisLexerProvider;
import de.mclsg.lsp.extensions.syntax_highlighting.CommonSyntaxHighlightingService;
import de.monticore.lang.sdbasis._lsp.language_access.SDBasisLanguageAccess;

public class SDBasisSyntaxHighlightingService extends CommonSyntaxHighlightingService {
    public SDBasisSyntaxHighlightingService(SDBasisLanguageAccess languageAccess) {
        registerProviders(languageAccess);
    }

    protected void registerProviders(SDBasisLanguageAccess languageAccess) {
        register(new SDBasisLexerProvider(languageAccess));
    }
}
