/* generated by template _lsp.DocumentInformationFilter*/

package de.monticore.lang.sd4development._lsp;

import de.mclsg.lsp.document_management.DocumentInformation;
import java.util.function.Predicate;

public class SD4DevelopmentDocumentInformationFilter implements Predicate<DocumentInformation> {

    @Override
    public boolean test(DocumentInformation info){
        return info != null && "SD4Development".equals(info.languageId);
    }

}