/* generated by template _lsp.features.rename.RenameProvider*/

package de.monticore.lang.sd4development._lsp.features.rename;

import de.mclsg.lsp.ISymbolUsageResolutionProvider;
import de.mclsg.lsp.document_management.DocumentManager;
import de.mclsg.lsp.features.rename.CommonRenameProvider;
import de.mclsg.lsp.features.reference.CommonReferencesProvider;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SD4DevelopmentRenameProvider extends CommonRenameProvider {
  public SD4DevelopmentRenameProvider(DocumentManager documentManager, ISymbolUsageResolutionProvider symbolUsageResolutionProvider, CommonReferencesProvider referencesProvider) {
    super(documentManager, symbolUsageResolutionProvider, referencesProvider);
  }
}
