/* generated by template _lsp.language_access.LspCoCoRunner*/

package de.monticore.lang.sd4development._lsp.language_access;

import de.monticore.lang.sdbasis._ast.ASTSDArtifact;
import de.monticore.lang.sd4development._lsp.*;
import de.monticore.lang.sd4development.SD4DevelopmentTool;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import de.mclsg.lsp.document_management.DocumentManager;
import de.se_rwth.commons.logging.Log;

public class SD4DevelopmentLspCoCoRunner implements de.mclsg.lsp.features.CoCoCheckProvider{
    private static final Logger logger = LoggerFactory.getLogger(SD4DevelopmentLspCoCoRunner.class);
    protected DocumentManager documentManager;
    protected SD4DevelopmentTool tool = new SD4DevelopmentTool();

    public SD4DevelopmentLspCoCoRunner(DocumentManager documentManager){
        this.documentManager = documentManager;
    }

    public void runAllCoCos(ASTSDArtifact ast){
        tool.runDefaultCoCos(ast);
        tool.runAdditionalCoCos(ast);
    }

    public void runCoCosForAllDocuments(){
        documentManager.getAllDocumentInformation(new SD4DevelopmentDocumentInformationFilter()).forEach(di -> {
                Log.enableFailQuick(false);

                if(di.ast != null){
                    Log.getFindings().clear();
                    try {
                      runAllCoCos((ASTSDArtifact) di.ast);
                    } finally {
                      di.findings.addAll(Log.getFindings());
                    }
                }
        });
    }

    public boolean needsSymbols(){
        return false;
    }
}
