/* generated by template _lsp.language_access.ArtifactScopeWithFindings*/

package de.monticore.lang.sd4development._lsp.language_access;

import de.monticore.lang.sdbasis._ast.ASTSDArtifact;
import de.monticore.lang.sd4development._symboltable.ISD4DevelopmentArtifactScope;
import de.se_rwth.commons.logging.Finding;
import java.util.*;

public class SD4DevelopmentArtifactScopeWithFindings{
    public final ASTSDArtifact originalAst;
    public final ISD4DevelopmentArtifactScope scope;
    public final List<Finding> findings = new ArrayList();

    public SD4DevelopmentArtifactScopeWithFindings(
        ASTSDArtifact originalAst,
        ISD4DevelopmentArtifactScope scope,
        List<Finding> findings
    ){
        this.originalAst = originalAst;
        this.scope = scope;
        if(findings != null){
            this.findings.addAll(findings);
        }
    }
}